### ISSUE TITLE
 lateinit property connectionHelper has not been initialized  package not working, while connecting

### ISSUE THREAD

**Issue by gijominuscule** [yagmure15/zebra_rfid_reader_sdk#2]
E/MethodChannel#borda/zebra_rfid_reader_sdk(17123): Failed to handle method call
E/MethodChannel#borda/zebra_rfid_reader_sdk(17123): kotlin.UninitializedPropertyAccessException: lateinit property connectionHelper has not been initialized
E/MethodChannel#borda/zebra_rfid_reader_sdk(17123): 	at com.borda.zebra_rfid_reader_sdk.ZebraRfidReaderSdkPlugin.onMethodCall(ZebraRfidReaderSdkPlugin.kt:73)
E/MethodChannel#borda/zebra_rfid_reader_sdk(17123): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#borda/zebra_rfid_reader_sdk(17123): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#borda/zebra_rfid_reader_sdk(17123): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#borda/zebra_rfid_reader_sdk(17123): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#borda/zebra_rfid_reader_sdk(17123): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#borda/zebra_rfid_reader_sdk(17123):

**Comment by JarrodLodge** [comment]
I suspect its to do with this update? https://docs.flutter.dev/release/breaking-changes/plugin-api-migration#basic-plugin
