### ISSUE TITLE
SDK not working in iOS

### ISSUE THREAD

**Issue by abiradamas** [yagmure15/zebra_rfid_reader_sdk#5]
I tried to implement the sdk, in android it's worked properly but in iOS it's not working.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getAvailableReaderList on channel borda/zebra_rfid_reader_sdk)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      MethodChannelZebraRfidReaderSdk.getAvailableReaderList (package:zebra_rfid_reader_sdk/src/zebra_rfid_reader_sdk_method_channel.dart:18:9)
<asynchronous suspension>
#2      _HomeDetailsViewState.getAvailableReaderList (package:smas/Screens/HomeDetails/HomeDetailsView.dart:323:20)
<asynchronous suspension>

**Comment by oBc9Hka** [comment]
I faced the same issue, updating pods in my project helped me.
